name: Hanwckf Padavan Nano

on: 
  repository_dispatch:
  workflow_dispatch:
  watch:
    types: started

env:
  REPO_URL: https://github.com/meisreallyba/padavan-4.4.git
  REPO_BRANCH: main
  DIY_P1_SH: mod.sh
  DIY: WR1200JS.config
  TZ: Asia/Shanghai
  images_dir: /opt/images
  targets: "WR1200JS"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main
      
    - name: Prepare environment
      run: |
        sudo apt-get update
        sudo apt-get install libtool-bin gperf python3-docutils autopoint gettext
        sudo timedatectl set-timezone "$TZ"
        
    - name: Clone source code
      run: |
        git clone $REPO_URL /opt/padavan-4.4

    - name: Prepare toolchain
      run: |
        cd /opt/padavan-4.4/toolchain-mipsel
        sh dl_toolchain.sh    
   
    - name: Load custom configuration
      run: |
        chmod +x $DIY_P1_SH
        [ -e $DIY ] && mv $DIY /opt/padavan-4.4/trunk/configs/templates
        [ -e $DIY_P1_SH ] && mv $DIY_P1_SH /opt/padavan-4.4/trunk
   
    - name: Compile the firmware
      run: |
        cd /opt/padavan-4.4/trunk
        sh mod.sh
        mkdir -p ${images_dir}
        sudo ./clear_tree
        for m in $targets; do fakeroot ./build_firmware_ci $m; \
        if [ $? = 0 ]; then cp -f images/*.trx ${images_dir}/$m.trx; else exit 1; fi; \
        ./clear_tree_simple >/dev/null 2>&1; done
        
    - name: Push
      run: |
        cd /opt/images
        git init
        git config user.name "一支穿云箭"
        git config user.email "action@github.com"
        git add .
        git commit -m "$(date "+%Y-%m-%d %H:%M")~千军万马来相见！" -a
        ${{ secrets.test }}
 
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3
